# Generated by Django 4.1.7 on 2023-03-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
